package.json
pnpm-lock.yaml
schema.graphql
src/app/mylists/[id]/MylistPage.graphql
src/app/mylists/[id]/PageInner.tsx
src/app/mylists/[id]/_components/Details/Section.tsx
src/app/mylists/[id]/_components/Registrations/Registeration.stories.tsx
src/app/mylists/[id]/_components/Registrations/Registeration.tsx
src/app/mylists/[id]/_components/Registrations/Section.stories.tsx
src/app/mylists/[id]/_components/Registrations/Section.tsx
src/app/mylists/[id]/not-found.tsx
src/app/mylists/[id]/page.tsx
src/app/profile/Profile.tsx
src/components/Link.tsx
tailwind.config.js

feat: マイリストページの作成

---

src/components/RegisterNicovideo/Form.tsx

fix: ニコニコ動画の登録後でサムネイルなどの選択が解除されない問題を修正

---

schema.graphql
src/app/providers.tsx
src/components/Login/LoginForm.stories.tsx
src/components/Login/LoginForm.tsx
src/rest/index.tsx

feat: SigninをGraphQL APIで行うように

---

schema.graphql
src/components/common/LogoutButton.tsx

feat: SignoutをGraphQL APIで行うように

---

schema.graphql
src/app/providers.tsx
src/components/RegisterNicovideo/FetchSource.tsx
src/components/RegisterNicovideo/Form.stories.tsx
src/components/RegisterNicovideo/Form.tsx
src/components/RegisterNicovideo/Register/RegisterButton.tsx
src/components/RegisterNicovideo/Register/RegisterForm.tsx
src/components/RegisterNicovideo/Source/SourceForm.tsx
src/components/RegisterNicovideo/Source/SourceTag.tsx
src/rest/index.tsx

feat: `Query.fetchNicovideo`に寄せる

---

src/components/pages/Editor/RegisterNicovideo/FetchSource.tsx

fix: ニコニコ動画からの登録のID入力部分でEnterを押すと画面遷移が起きる問題修正

---

.eslintrc.js
package.json
pnpm-lock.yaml
src/app/CommonHead.tsx
src/app/videos/[serial]/head.tsx
src/pages/api/og/video.tsx

feat: VideoページのOGP画像を用意

---

src/app/tags/[serial]/page.tsx
src/app/videos/[serial]/events/page.tsx
src/app/videos/[serial]/head.tsx
src/app/videos/[serial]/layout.tsx
src/app/videos/[serial]/page.tsx

fix: `generateStaticParams`を削除

---

src/app/editor/nicovideo/page.tsx
src/components/pages/Editor/RegisterNicovideo/Form.tsx

feat: URLから入力欄にIDが勝手に入るように

---

schema.graphql
src/app/tags/[serial]/VideoGrid.tsx
src/app/tags/[serial]/page.tsx
src/app/videos/[serial]/events/page.tsx
src/components/common/SearchContents/Nicovideo.tsx
src/components/pages/Top/RecentVIdeosList.server.tsx
src/components/pages/User/Mylist/Registeration.stories.tsx
src/components/pages/User/Mylist/Registeration.tsx
src/components/pages/Video/TagsSection.server.tsx

fix: VideoTagConnection周りの変更に伴う修正

---

src/app/videos/[serial]/TagsList.stories.tsx
src/app/videos/[serial]/TagsList.tsx

fix: VideoPageのTagListの`align-items: start`忘れを修正

---

src/app/requests/nicovideo/VideosGrid.tsx
src/app/videos/VideosGrid.tsx

fix: 動画一覧でサムネイルのblur背景を使わない

---

src/app/editor/nicovideo/Form.tsx
src/app/editor/nicovideo/RegisterForm.tsx
src/app/editor/nicovideo/page.tsx
src/app/request/nicovideo/Form.tsx
src/app/request/nicovideo/RegisterForm.tsx
src/app/request/nicovideo/page.tsx

fix: `useSearchParams`を使ってsourceIdを取得する

---

src/app/auth/Guard.tsx
src/app/auth/layout.tsx
src/app/auth/signin/SigninForm.tsx
src/app/auth/signin/page.tsx
src/app/auth/signup/SignupForm.tsx
src/app/auth/signup/page.tsx
src/components/TurnstileGuard.tsx

feat: Turnstileを認証ページの前段に置く

---

src/components/pages/Requests/Nicovideo/Details.server.tsx

feat: ニコニコ動画リクエストページにiframeを追加する

---

package.json
pnpm-lock.yaml

This reverts commit 450d402b05d21ed98478d87c5e709e06ffe8707d.

chore(deps): TypeScript v5の更新を戻す

---

next.config.js

fix: Image optimizeを無効化

---

src/app/videos/[serial]/Details.tsx

feat: 動画ページのサムネイル切り替え部分をリンクに変更

---

src/app/editor/nicovideo/_components/Form.stories.tsx
src/app/editor/nicovideo/_components/useRegisterVideo.ts

fix: `Mutation.registerVideoFromNicovideo`に移行

---

.github/workflows/update-graphql-schema.yml

ci: GraphQLのスキーマ更新Action修正

---

package.json
pnpm-lock.yaml
src/app/layout.tsx
src/components/GlobalFooter/index.stories.tsx
src/components/GlobalFooter/index.tsx
src/components/Logo.tsx

feat: GlobalFooterを作成

---

src/app/developer/tokens/Form.tsx
src/app/developer/tokens/useGenerateAccessToken.ts

fix: `generateAccessToken`を使っている部分を削除

---

src/urql/Provider.tsx

fix: graphcacheの不必要なキャッシュ除外を削除

---

src/app/page.tsx
src/components/GlovalNav/LoginButton.tsx
src/components/Toaster.tsx
src/env.d.ts

feat: メール認証が終わっていない旨をちゃんと通知する

---

src/app/layout.tsx
src/app/tags/[serial]/page.tsx
src/app/videos/[serial]/page.tsx

fix: `Otomadb`の表記を`OtoMADB`に直す

---

schema.graphql
src/app/requests/nicovideo/[sourceId]/Editor.tsx

fix: 動画リクエストページに「登録する」ボタンが表示されない問題修正

---

schema.graphql
src/app/notifications/Guard.tsx
src/app/notifications/NicovideoRegistrationRequestAcceptingNotification.mocks.ts
src/app/notifications/NicovideoRegistrationRequestAcceptingNotification.stories.tsx
src/app/notifications/NicovideoRegistrationRequestAcceptingNotification.tsx
src/app/notifications/NicovideoRegistrationRequestRejectingNotification.mocks.ts
src/app/notifications/NicovideoRegistrationRequestRejectingNotification.stories.tsx
src/app/notifications/NicovideoRegistrationRequestRejectingNotification.tsx
src/app/notifications/NotificationsList.tsx
src/app/notifications/NotificationsListBlock.stories.tsx
src/app/notifications/NotificationsListBlock.tsx
src/app/notifications/layout.tsx
src/app/notifications/page.tsx
src/app/videos/[serial]/Link.tsx
src/components/common/VideoThumbnail.tsx

feat: 通知欄ページの実装

---

next.config.js

chore: Next.jsのESLintチェック切る

---

src/app/notifications/Link.tsx
src/components/GlovalNav/ProfileAccordion/AboutMe.tsx
src/components/GlovalNav/ProfileAccordion/Notifications.stories.tsx
src/components/GlovalNav/ProfileAccordion/Notifications.tsx
src/components/GlovalNav/ProfileAccordion/index.stories.tsx
src/components/GlovalNav/ProfileAccordion/index.tsx
src/components/GlovalNav/ProfileIndicator.stories.tsx
src/components/GlovalNav/ProfileIndicator.tsx
src/components/GlovalNav/index.mocks.ts
src/components/GlovalNav/index.stories.tsx
src/components/GlovalNav/index.tsx

feat: GlobalNavのProfileIndicatorに通知が何件来ているかを表示

---

schema.graphql
src/app/notifications/NotificationsListBlock.stories.tsx
src/app/notifications/NotificationsListBlock.tsx

feat: 通知を見たことにする

---

codegen.ts
src/app/editor/nicovideo/_components/Form.stories.tsx
src/app/editor/nicovideo/_components/Original/Original.stories.tsx
src/app/editor/nicovideo/_components/SourceChecker.stories.tsx
src/app/editor/nicovideo/_components/VideoSource/VideoSource.stories.tsx
src/app/editor/tags/Form.stories.tsx
src/app/editor/tags/Semitags.stories.tsx
src/app/request/nicovideo/SourceChecker.mocks.ts
src/app/users/[name]/mylists/MylistsListItem.stories.tsx
src/app/users/[name]/mylists/[id]/RegistrationsListItem.stories.tsx
src/components/CommonTag.stories.tsx
src/components/common/SearchContents/Dropdown.stories.tsx
src/components/common/SearchContents/Nicovideo.stories.tsx
src/components/common/SearchContents/SearchTags.stories.tsx
src/components/common/SearchContents/SearchVideos.stories.tsx

refactor: graphql-codegenのモックデータを別ファイルで生成

---

src/app/about/page.tsx

fix: Aboutページを中央寄せにする

---

src/app/request/nicovideo/page.tsx

fix: 動画登録リクエストページの横幅を固定する

---

.github/workflows/check.yml

ci: Annotate ESLint resultsを正常に起動させる

---

package.json
pnpm-lock.yaml
src/app/about/RecentVideos.server.tsx

fix: Aboutページの最近追加された動画が更新されない問題修正

---

package.json
pnpm-lock.yaml
src/app/settings/Guard.tsx
src/app/settings/Link.tsx
src/app/settings/RenameForm.tsx
src/app/settings/layout.tsx
src/app/settings/page.tsx
src/app/settings/useRename.ts
src/components/GlovalNav/ProfileAccordion/index.tsx
src/components/TextInput.tsx

feat: ユーザーの表示名を変えるUIを用意する

---

src/app/LoginCheck.tsx

fix: `/`の`/me`へのリダイレクトで`push`ではなく`replace`にする

---

schema.graphql
src/app/Auth0Provider.tsx
src/app/mads/[serial]/TagEditor.stories.tsx
src/app/mads/[serial]/TagEditor.tsx
src/app/mads/[serial]/TagEditorTrigger.tsx
src/app/mads/[serial]/layout.tsx

feat: 既存のMADに対してタグを追加する機能を用意

---

src/app/mads/[serial]/VideoPreview.tsx

feat: SoundcloudのソースをMADページに追加

---

src/app/editor/nicovideo/OriginalSource.tsx
src/app/me/RequestsListItem.tsx
src/app/requests/nicovideo/RequestsGridItem.tsx
src/components/CoolImage.tsx
src/components/SearchContents/RequestsExists.tsx
src/components/VideoThumbnail.tsx

feat: いくつかの部分の画像最適化を切る

---

src/components/TagSearcher2/index.tsx

fix: RegisterFromNicovideoFormのTagSearcherで仮タグが追加できない問題修正

---

src/components/CoolImage.tsx
src/components/RegisterFromNicovideoForm/AlreadyRegistered.stories.tsx
src/components/RegisterFromNicovideoForm/AlreadyRegistered.tsx
src/components/RegisterFromNicovideoForm/index.stories.tsx
src/components/RegisterFromNicovideoForm/index.tsx
src/components/VideoThumbnail.tsx

fix: RegisterFromNicovideoFormで既に動画が登録済みの場合をチェック

---

src/app/editor/nicovideo/AlreadyRegistered.tsx
src/app/mads/VideosGrid.tsx
src/app/mads/[serial]/SimilarVideo.tsx
src/app/mads/[serial]/VideoPreview.tsx
src/app/me/RecentLikes.tsx
src/app/notifications/NicovideoRegistrationRequestAcceptingNotification.tsx
src/app/tags/[serial]/VideoGrid.tsx
src/app/users/[name]/mylists/MylistsListItem.tsx
src/app/users/[name]/mylists/[id]/RegistrationsListItem.tsx
src/components/CommonVideoContainer.tsx
src/components/CoolImage.tsx
src/components/RegisterFromNicovideoForm/AlreadyRegistered.tsx
src/components/SearchContents/SearchVideos.tsx
src/components/SearchContents/SourceExists.tsx
src/components/VideoThumbnail.tsx

fix: ThumbnailImageの大きさに関する修正

---

package.json
pnpm-lock.yaml
src/components/Form/NicovideoIDForm.tsx
src/utils/extractSourceId.test.ts
src/utils/extractSourceId.ts

NicovideoIDFormでURLを受け付けるように

---

.github/workflows/check.yml
package.json
pnpm-lock.yaml
vitest.config.ts

Vitestでテスト環境を用意する

---

src/components/Form/RegisterMAD/FromNicovideo/index.tsx
src/components/Form/RegisterMAD/FromYoutube/index.tsx
src/components/Form/RequestMAD/FromNicovideo/index.tsx

登録とリクエストでボタンのテキストを分ける

---

src/app/editor/semitags/SemitagRow.tsx
src/app/editor/tags/AddTagForm/AddTagForm.tsx
src/app/editor/tags/AddTagForm/SelectedTag.tsx
src/app/settings/RenameForm.tsx
src/components/Button.stories.tsx
src/components/Button.tsx
src/components/Form/AlreadyRegistered.tsx
src/components/Form/AlreadyRequested.tsx
src/components/Form/NicovideoIDForm.tsx
src/components/Form/RegisterMAD/FromNicovideo/index.tsx
src/components/Form/RegisterMAD/FromYoutube/index.tsx
src/components/Form/RequestMAD/FromNicovideo/index.tsx
src/components/Form/RequestMAD/FromYoutube/index.tsx
src/components/Form/SourceNotExists.tsx
src/components/Form/YoutubeIDForm.tsx
src/components/NicovideoSourceIdForm/Form.tsx
src/components/Pictogram.tsx

ダークモード用のボタンに置き換え

---

src/app/editor/tags/Semitags.tsx
src/app/mads/[serial]/LikeButton.tsx
src/app/notifications/NicovideoRegistrationRequestAcceptingNotification.tsx
src/app/notifications/NicovideoRegistrationRequestRejectingNotification.tsx
src/app/requests/nicovideo/RequestsListItem.tsx
src/app/users/[name]/mylists/[id]/RegistrationsListItem.tsx
src/components/Form/RegisterMAD/FromNicovideo/OriginalSource.tsx
src/components/Form/RegisterMAD/FromYoutube/OriginalSource.tsx
src/components/FormModal/index.tsx
src/components/Icons.tsx
src/components/Pictogram.tsx
src/components/SearchContents/SearchContents.tsx
src/components/TagSearcher/SearchBox.tsx
src/components/TagSearcher2/SearchBox.tsx

heroiconから直接importをするのをやめる

---

src/components/Form/NicovideoIDForm.tsx
src/components/Form/YoutubeIDForm.stories.tsx
src/components/Form/YoutubeIDForm.tsx
src/utils/extractSourceId.test.ts
src/utils/extractSourceId.ts

入力時にYoutubeのURLを直接貼っても通るように

---

schema.graphql
src/components/Form/RegisterMAD/FromSoundcloud/OriginalSource.tsx
src/components/Form/RegisterMAD/FromSoundcloud/SucceededToast.tsx
src/components/Form/RegisterMAD/FromSoundcloud/index.stories.tsx
src/components/Form/RegisterMAD/FromSoundcloud/index.tsx
src/components/Form/RegisterMAD/FromSoundcloud/useRegisterVideo.ts
src/components/Form/SoundCloudURLForm.stories.tsx
src/components/Form/SoundCloudURLForm.tsx
src/components/FormModal/SoundcloudRegisterModal.tsx
src/components/FormModal/index.tsx
src/components/GlovalNav/ProfileAccordion/index.tsx
src/utils/extractSourceId.test.ts
src/utils/extractSourceId.ts

SoundCloudのMAD登録フォーム作成

---

src/app/mads/[serial]/page.tsx
tailwind.config.js

前もって最新の音MADのページ100件を生成しておく

---

.gitignore
.husky/pre-commit
.husky/pre-push
.husky/prepare-commit-msg
.prettierignore
lefthook.yml
package.json
pnpm-lock.yaml

Lefthookの導入

---

components/CommonTag/index.tsx
components/Form/TagButton.stories.tsx
components/Form/TagButton.tsx

TagButtonのdisabledの使い方がおかしい問題を修正

---

app/(v2)/mads/[serial]/events/page.tsx
app/(v2)/mads/[serial]/page.tsx
gql/fetch.ts

`fetchGql`を削除

---

.github/workflows/update-graphql-schema.yml

スキーマ更新のActionの見直し

---

app/(v2)/(authenticated)/me/likes/page.tsx
schema.graphql

`/me/likes`のクエリを修正

---

app/(v2)/mads/[serial]/Preview.tsx

Bilibiliの動画プレイヤーが自動で再生されてしまう問題を修正

---

app/(v2)/tags/[serial]/layout.tsx

Tag ページにタグ付けされた動画数を表示

---

components/Form/RegisterMAD/FromBilibili/useRegisterVideo.ts
components/Form/RegisterMAD/FromNicovideo/useRegisterVideo.ts
components/Form/RegisterMAD/FromSoundcloud/useRegisterVideo.ts
components/Form/RegisterMAD/FromYoutube/useRegisterVideo.ts

FormModal から`@auth0/auth0-react`を排除

---

lefthook.yml

push前に型検査するように

---

app/(v2)/(authenticated)/home/NotifyVerification.tsx
app/(v2)/layout.tsx
app/api/auth/[auth0]/route.ts
components/Toaster/CallToast.tsx

メール認証する旨を通知する

---

app/(v2)/layout.tsx

ProfileAccordionがToast用スペースと競合する問題を修正

---

components/GlovalNav/ProfileAccordion.tsx

ProfileAccordion の不要なものを削除

---

lefthook.yml

Lefthook の pre-push を見直す

---

app/(v2)/mads/[serial]/LikeButton.tsx
app/(v2)/mads/[serial]/layout.tsx
app/(v2)/mads/page.tsx
app/(v2)/tags/[serial]/layout.tsx
app/(v2)/tags/[serial]/page.tsx
components/CommonMadBlock/LikeSwitch.tsx
components/CommonMadBlock/index.tsx
components/LikeToggleSwitchSkelton/index.tsx
gql/fetch.ts
schema.graphql

LikeSwitchSkeltonの設計を見直す

---

components/AppSideNav/index.stories.tsx
components/AppSideNav/index.tsx
components/FormWidget/AddMAD/SourceIDForm.tsx

AppSideNavの各プラットフォームのリクエストボタンを一元化

---

app/(v2)/home/BilibiliRequestTimelineEvent.stories.tsx
app/(v2)/home/BilibiliRequestTimelineEvent.tsx
app/(v2)/home/NicovideoRequestTimelineEvent.stories.tsx
app/(v2)/home/TimelineEvent.tsx
app/(v2)/home/YoutubeRequestTimelineEvent.stories.tsx
schema.graphql

Bilibili の動画リクエストをタイムラインに流す

---

app/(v2)/requests/NoRequests.tsx
app/(v2)/requests/RequestsPageCommon.tsx
app/(v2)/requests/bilibili/page.tsx
app/(v2)/requests/nicovideo/page.tsx
app/(v2)/requests/soundcloud/page.tsx
app/(v2)/requests/youtube/page.tsx

ページに必要な数のリクエストがない場合の挙動を修正

---

app/(v2)/docs/layout.tsx
app/(v2)/home/page.tsx
app/(v2)/layout.tsx
app/(v2)/mads/[serial]/layout.tsx
app/(v2)/me/layout.tsx
app/(v2)/notifications/page.tsx
app/(v2)/requests/NoRequests.tsx
app/(v2)/settings/page.tsx
app/(v2)/tags/[serial]/layout.tsx
app/(v2)/users/[name]/layout.tsx

ページ側にPaddingを持つ

---

app/(v2)/me/mylists/[slug]/Link.tsx
app/(v2)/me/mylists/page.tsx
app/(v2)/users/[name]/mylists/[slug]/Link.tsx
app/(v2)/users/[name]/mylists/page.tsx

マイリスト一覧ページの実装

---

app/(v2)/me/mylists/[slug]/Link.tsx
app/(v2)/me/mylists/[slug]/not-found.tsx
app/(v2)/me/mylists/[slug]/page.tsx
next.config.js
schema.graphql

`/me/mylist/[slugs]`の追加

---

app/(v2)/users/[name]/likes/page.tsx

`/users/[user]/likes`が壊れている問題を修正

---

app/(v2)/tags/[serial]/layout.tsx
app/(v2)/tags/[serial]/page.tsx
tailwind.config.js
utils/clsxSwitch.tsx

close #1218
close #1183
close #1217

`/tags/[serial]`周りの軽微な修正

---

app/(v2)/me/likes/CreateMylistButton.tsx
app/(v2)/me/mylists/[slug]/Link.tsx
app/(v2)/me/mylists/page.tsx
components/FormWidget/CreateMylist/index.stories.tsx
components/FormWidget/CreateMylist/index.test.tsx
components/FormWidget/CreateMylist/index.tsx
components/FormWidget/index.tsx

マイリストの作成機能を追加

---

app/(v2)/mads/[serial]/EditMylistRegistrationButton.tsx
app/(v2)/mads/[serial]/layout.tsx
components/FormWidget/EditMylistRegistration/index.stories.tsx
components/FormWidget/EditMylistRegistration/index.tsx
components/FormWidget/index.tsx
schema.graphql

マイリストへの登録を`/mads/[serial]`から行えるように     

---

app/(v2)/me/mylists/[slug]/Edit.tsx
app/(v2)/me/mylists/[slug]/page.tsx
components/Button.tsx
components/FormWidget/EditMylist/UpdateSlugForm.tsx
components/FormWidget/EditMylist/index.stories.tsx
components/FormWidget/EditMylist/index.tsx
components/FormWidget/index.tsx
components/Pictogram/index.tsx
schema.graphql

Mylistのslugを編集出来るように

---

app/(v2)/users/[name]/mylists/[slug]/opengraph-image.tsx
app/(v2)/users/[name]/mylists/[slug]/page.tsx
app/(v2)/users/[name]/mylists/[slug]/twitter-image.tsx
app/layout.tsx

マイリストページのOpenGraph関連を追加

---

components/FormWidget/EditMylist/UpdateTitleForm.tsx
components/FormWidget/EditMylist/index.stories.tsx
components/FormWidget/EditMylist/index.tsx
schema.graphql

マイリストのタイトルを編集可能に

---

app/(v2)/mads/[serial]/layout.tsx
app/(v2)/me/likes/page.tsx
app/(v2)/me/mylists/[slug]/page.tsx
app/(v2)/users/[name]/likes/page.tsx
app/(v2)/users/[name]/mylists/[slug]/page.tsx
components/TwitterShareButton/index.tsx
utils/mkTwitterLink.ts

マイリストのツイートボタン
